# Generated by Django 3.2.15 on 2022-10-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_user_hide_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
